export const TAU = Math.PI * 2;
export const EPS = 1e-6;
export const clamp = (v, min, max) => v < min ? min : v > max ? max : v;
export const clamp01 = (v) => v < 0 ? 0 : v > 1 ? 1 : v;
export const lerp = (a, b, t) => a + (b - a) * t;
export const lerpClamped = (a, b, t) => a + (b - a) * clamp01(t);
export const invLerp = (a, b, v) => (b - a !== 0) ? (v - a) / (b - a) : 0;
export const remap = (inA, inB, outA, outB, v) => lerp(outA, outB, invLerp(inA, inB, v));
export const wrap = (v, min, max) => ((((v - min) % (max - min)) + (max - min)) % (max - min)) + min;
export const normalizeAngle = (a) => wrap(a + Math.PI, 0, TAU) - Math.PI;
export const angleDelta = (a, b) => normalizeAngle(b - a);
export function approachAngle(current, target, maxStep) { const d = angleDelta(current, target); return Math.abs(d) <= maxStep ? target : current + Math.sign(d) * maxStep; }
export const damp = (current, target, lambda, dt) => lerp(current, target, 1 - Math.exp(-lambda * dt));
export const smoothstep = (t) => { t = clamp01(t); return t * t * (3 - 2 * t); };
export const smootherstep = (t) => { t = clamp01(t); return t * t * t * (t * (t * 6 - 15) + 10); };
export const dist2 = (x1, y1, x2, y2) => { const dx = x2 - x1; const dy = y2 - y1; return dx * dx + dy * dy; };
export const dist = (x1, y1, x2, y2) => Math.sqrt(dist2(x1, y1, x2, y2));
export const randRange = (min, max) => min + Math.random() * (max - min);
export const randInt = (min, max) => Math.floor(min + Math.random() * (max - min + 1));
export { shade } from "./color.js";
